# ワークフローの名前
name: Frontend Build Test

on:
  # 手動実行
  workflow_dispatch:
    branches:
      - main
      - develop
  ## プルリク実行
  #pull_request:
  #  branches:
  #    - develop
  # ブランチにpushしたら実行
  push:
    branches:
      - main

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['14.x']

    # 各ステップの実行
    steps:

      # チェックアウト
      - uses: actions/checkout@v2

      # 使用するnodeのバージョンを指定
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # パッケージのインストールとアプリのビルド
      - name: install and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build:test
        env:
          CI: true

      # git config
      - name: git config
        run: |
          git config --global pull.rebase false
          git config --local user.email "tashima.toru@gmail.com"
          git config --local user.name "田島 徹"

      # ビルドしたjsをreleaseブランチにコミット
      - name: git commit push
        working-directory: ./frontend/build
        run: |
          git add . -f
          git checkout release
          
